### ISSUE TITLE
imu extrinsics are not used

### ISSUE THREAD

**Issue by shishiteng** [ChaoqinRobotics/LINS---LiDAR-inertial-SLAM#10]
I searched for two variables `init_rbl` and `init_tbl` in the code but found that they were not used actually. Is this a bug?

**Comment by narutojxl** [comment]
In  [imu callback() ](https://github.com/ChaoqinRobotics/LINS---LiDAR-inertial-SLAM/blob/master/lins/src/lib/Estimator.cpp#L132), author thinks the roll and pitch degrees between imu and laser are zero, the yaw from laser to imu  is  **imu_misalign_angle** in config file.

**Comment by ChaoqinRobotics** [comment]
Thanks for your question. LINS program here is just a simplified version. These two values are used in the full program. We will use init_rbl and init_tbl  in the following update.

**Comment by shishiteng** [comment]
> Thanks for your question. LINS program here is just a simplified version. These two values are used in the full program. We will use init_rbl and init_tbl in the following update.

Got it! Looking foward the new update!

**Comment by bryantaoli** [comment]
> Thanks for your question. LINS program here is just a simplified version. These two values are used in the full program. We will use init_rbl and init_tbl in the following update.

When will there be an update?
