### ISSUE TITLE
Ft in code is different from that in paper

### ISSUE THREAD

**Issue by szm88** [ChaoqinRobotics/LINS---LiDAR-inertial-SLAM#5]
According to code, I found that Ft should be：
<img width="347" alt="1" src="https://user-images.githubusercontent.com/11388009/82280045-91f8e580-99c0-11ea-97a7-fb79863f6164.png">

**Comment by ChaoqinRobotics** [comment]
Thank you for pointing it out! It is a typo. Please follow the code.

**Comment by szm88** [comment]
OK
