### ISSUE TITLE
distance of point to line wrt point jacobian

### ISSUE THREAD

**Issue by narutojxl** [ChaoqinRobotics/LINS---LiDAR-inertial-SLAM#7]
Hi doctor qin, when we calculating the distance of point P0 to line(P1 - P2) wrt P0 jacobian, the jacobian why is [this form](https://github.com/ChaoqinRobotics/LINS---LiDAR-inertial-SLAM/blob/master/lins/include/StateEstimator.hpp#L1044)?  
Let we 
![2020-05-26 23-06-35屏幕截图](https://user-images.githubusercontent.com/6205343/82917924-a03d9780-9fa6-11ea-9b5e-15783d64a238.png)
How you get the formal like above,thanks very very much !

**Comment by ChaoqinRobotics** [comment]
Thanks for asking. I would provide a detailed derivation in the future. A littble bit busy in recent month : )

**Comment by narutojxl** [comment]
Thanks very much, looking forward!

**Comment by narutojxl** [comment]
Sorry, my mistake for writing the error formua of  d, it shoule be like this:
![2020-06-10 17-45-20屏幕截图](https://user-images.githubusercontent.com/6205343/84253390-72c62180-ab42-11ea-86e9-e3f069401ada.png)
The jacobian in code is correct, thanks @qin :)
